### PR TITLE
Update chocolatey package to 1.5.0

### PR DESCRIPTION
**Pull request by jasongin**

### CODE REVIEW

**Comment by jasongin** [comment]
@molant I think you'll need to publish the update to chocolatey since you are the maintainer.

**Comment by molant** [comment]
I've published the new version and it's now under review:
image

And the url to check: https://chocolatey.org/packages/nvs/1.5.0

**Comment by jasongin** [comment]
Thanks!

**Comment by molant** [comment]
@jasongin Pending approval: https://chocolatey.org/packages/nvs/1.5.1

**Pull request merged**
