### PR TITLE
add 'outdated' command

### PR DESCRIPTION
**Pull request by rmg**
A variant of `nvs ls` that includes whether there is a newer release of the same semver-major versions as installed.

Example output and usage scenario:
```
$ nvs outdated
>#node/8.7.0/x64
  node/6.10.3/x64 (Boron) [upgrade available: node/6.11.4]
  node/4.8.4/x64 (Argon)
$ nvs upgrade 6
Upgrading node/6.10.3/x64 to 6.11.4...
Extracting  [##############################################] 100%
Added at: ~/.nvs/node/6.11.4/x64/bin/node
Skipping  : npm (source=target=3.10.10)
- ~/.nvs/node/6.10.3/x64
$ nvs outdated
>#node/8.7.0/x64
  node/6.11.4/x64 (Boron)
  node/4.8.4/x64 (Argon)
```

### CODE REVIEW

**Comment by ljharb** [comment]
I like keeping the latest of every minor installed; is there a way I could use that command for that as well?

**Comment by jasongin** [comment]
Nice. This looks good... but there is one failing unit test caught by the CI. Can you look into that?

I had previously avoided the semver dependency to keep the bundled dependencies to a minimum. But semver is something that will be generally useful for a lot of scenarios, so there's probably no point in avoiding it any longer. (There is some code in `version.js` for comparing versions that could be simplified using semver, but you don't need to do that now.)

**Comment by jasongin** [comment]
> I like keeping the latest of every minor installed

Maybe there could be an option to the `upgrade` and `outdated` commands that checks for minor instead of major updates?

**Comment by jasongin** [comment]
> `node/6.10.3/x64 (Boron) [update available: node/6.11.4]`

Should this say "_upgrade_ available" to be consistent with the `nvs upgrade` command terminology?

**Comment by rmg** [comment]
> I had previously avoided the semver dependency to keep the bundled dependencies to a minimum. But semver is something that will be generally useful for a lot of scenarios, so there's probably no point in avoiding it any longer.

That's pretty much what I said in the commit message for adding it :-)

**Comment by rmg** [comment]
@jasongin I've updated the working and fixed the failing test.

**Comment by rmg** [comment]
> I like keeping the latest of every minor installed; is there a way I could use that command for that as well?

@ljharb this would be relatively trivial to implement internally (literally change the `^` in this PR to a `~`), but I'm not sure how best to expose that.

One interesting and complicated approach would be if the requested version was stored as part of the installation such that `nvs add 8` noted that semver-major was specified and `nvs add 8.11` noted that semver-minor was specified, then even though (at the time of this writing) they both install `8.11.3`, only the one installed as `8` would see `8.12.x` as an upgrade but both would consider `8.11.4` to be an upgrade.

**Comment by jasongin** [comment]
> I like keeping the latest of every minor installed; is there a way I could use that command for that as well?

In #167 I have enhanced this command to show both minor and patch upgrade versions when available, in a more concise format.

Example output from nvs outdated:
```
 node/12.18.2/x64
 node/12.16.2/x64 [~12.16.3] [^12.18.2]
 node/10.20.1/x64 [^10.21.0]
```

Closing this PR because it is superseded by that one.

**Pull request closed without merging**
