### PR TITLE
add support for Macs with Apple M1 Chip

### PR DESCRIPTION
**Pull request by geo4orce**

### CODE REVIEW

**Comment by brodybits** [comment]
any updates or status?

**Review by jasongin — COMMENTED** [review]
Sorry for the delay in reviewing... I am confused about the reason for this change.

It looks like this will cause nvs to always download the x64 build of node.js on Mac M1 systems. But Mac arm64 node.js builds are available starting with v16, and https://github.com/jasongin/nvs/pull/220 from last year added support for downloading those.

Can you (or anyone) explain what is the problem this is intended to solve? Unfortunately I don't have access to an M1 Mac to test this.

**Comment by martijnlutgens** [comment]
When I try to install a node version below 16 I get "Platform package not available for version: node/14.21.3/arm64". NVS tries to find a arm64 version but an arm64 version is not available for node versions below 16. Could you fix this by downloading the x64 version for node versions below node 16.

**Comment by geo4orce** [comment]
I think this is no longer relevant. Closing.

**Pull request closed without merging**
