### PR TITLE
Proxy support

### LINKED ISSUE #55: Proxy settings
Hi @jasongin ,

Actually, I have a problem to add a node.js version. Here my error:
```bash
nvs add v7
Failed to download index: https://nodejs.org/dist/index.json
getaddrinfo EAI_AGAIN nodejs.org:443
```
I think the problem is the proxy settings. But I didn't seen a proxy configuration in your documentation.
I already configured the "proxy", "http_proxy" env but I doesn't work.

Have you an idea ?

Thanks for your work ;) 
See you

### PR DESCRIPTION
**Pull request by eternalphane**
Support sending request through proxy set in `http_proxy`/`https_proxy`.

Additional dependencies:
- [http-proxy-agent](https://www.npmjs.com/package/http-proxy-agent)
- [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent)

Fix #55

### CODE REVIEW

**Comment by eternalphane** [comment]
`ts-check` failure can be solved by the following patch. I'll push a commit if it really matters.
```diff
diff --git a/lib/download.js b/lib/download.js
index 861b1e3..b75dbc4 100644
--- a/lib/download.js
+++ b/lib/download.js
@@ -49,7 +49,7 @@ function downloadFileAsync(filePath, fileUri) {
 					? process.env.https_proxy || process.env.HTTPS_PROXY
 					: process.env.http_proxy || process.env.HTTP_PROXY;
 				const Agent = secure ? HttpsProxyAgent : HttpProxyAgent;
-				/** @type {RequestOptions} */
+				/** @type {any} */
 				let opt = url.parse(fileUri);
 				if (proxy) opt.agent = new Agent(proxy);
 				httpGet(opt, (res) => {
diff --git a/lib/list.js b/lib/list.js
index 6c2edb7..6d5245a 100644
--- a/lib/list.js
+++ b/lib/list.js
@@ -290,7 +290,7 @@ function getNodejsRemoteVersionsAsync(remoteName, remoteUri) {
 		? process.env.https_proxy || process.env.HTTPS_PROXY
 		: process.env.http_proxy || process.env.HTTP_PROXY;
 	const Agent = secure ? HttpsProxyAgent : HttpProxyAgent;
-	/** @type {RequestOptions} */
+	/** @type {any} */
 	let opt = url.parse(remoteIndexUri);
 	if (proxy) opt.agent = new Agent(proxy);
 	return new Promise((resolve, reject) => {
diff --git a/package-lock.json b/package-lock.json
index d690744..4dc573a 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,6 +1,6 @@
 {
 	"name": "nvs",
-	"version": "1.5.3",
+	"version": "1.5.4",
 	"lockfileVersion": 1,
 	"requires": true,
 	"dependencies": {
@@ -487,9 +487,9 @@
 			"dev": true
 		},
 		"@types/node": {
-			"version": "10.11.7",
-			"resolved": "https://registry.npmjs.org/@types/node/-/node-10.11.7.tgz",
-			"integrity": "sha512-yOxFfkN9xUFLyvWaeYj90mlqTJ41CsQzWKS3gXdOMOyPVacUsymejKxJ4/pMW7exouubuEeZLJawGgcNGYlTeg==",
+			"version": "13.7.7",
+			"resolved": "https://registry.npmjs.org/@types/node/-/node-13.7.7.tgz",
+			"integrity": "sha512-Uo4chgKbnPNlxQwoFmYIwctkQVkMMmsAoGGU4JKwLuvBefF0pCq4FybNSnfkfRCpC7ZW7kttcC/TrRtAJsvGtg==",
 			"dev": true
 		},
 		"acorn": {
@@ -6174,9 +6174,9 @@
 			"dev": true
 		},
 		"typescript": {
-			"version": "3.1.3",
-			"resolved": "https://registry.npmjs.org/typescript/-/typescript-3.1.3.tgz",
-			"integrity": "sha512-+81MUSyX+BaSo+u2RbozuQk/UWx6hfG0a5gHu4ANEM4sU96XbuIyAB+rWBW1u70c6a5QuZfuYICn3s2UjuHUpA==",
+			"version": "3.7.2",
+			"resolved": "https://registry.npmjs.org/typescript/-/typescript-3.7.2.tgz",
+			"integrity": "sha512-ml7V7JfiN2Xwvcer+XAf2csGO1bPBdRbFCkYBczNZggrBZ9c7G3riSUeJmqEU5uOtXNPMhE3n+R4FA/3YOAWOQ==",
 			"dev": true
 		},
 		"uglify-js": {
diff --git a/package.json b/package.json
index 6071237..a51025c 100644
--- a/package.json
+++ b/package.json
@@ -18,7 +18,7 @@
 		"url": "https://github.com/jasongin/nvs"
 	},
 	"devDependencies": {
-		"@types/node": "^10.11.7",
+		"@types/node": "^13.7.7",
 		"ava": "^1.4.1",
 		"eslint": "^5.16.0",
 		"eslint-config-standard": "^12.0.0",
@@ -28,7 +28,7 @@
 		"eslint-plugin-standard": "^4.0.0",
 		"nyc": "^14.1.1",
 		"rewire": "^2.5.2",
-		"typescript": "^3.1.3"
+		"typescript": "^3.7.2"
 	},
 	"ava": {
 		"files": "test/*Tests.js"
diff --git a/tsconfig.json b/tsconfig.json
index 5c5fd1a..5c5b070 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -4,6 +4,7 @@
                "allowJs": true,
                "moduleResolution": "node",
                "resolveJsonModule": true,
+               "allowSyntheticDefaultImports": true,
                "types": ["node"],
                "target":"es2017"
        },
```

**Comment by jasongin** [comment]
Thanks for the PR! I like that this is much lighter weight than the [other PR](https://github.com/jasongin/nvs/pull/84) that added proxy support using the `request` package.

I see `http-proxy-agent` and `https-proxy-agent`, along with the existing `follow-redirects` dependency, depend on some of the same packages, which causes a lot of files to be duplicated in the repo. Can we avoid that duplication, perhaps by moving the `node_modules` directory up one level? I don't mind if that causes some extra manual steps to update the dependencies; it's not something that should need to be done often.

Also the ts-check issues do need to be fixed. That diff looks fine.

**Comment by eternalphane** [comment]
Tried to update `follow-redirects` to `v1.10.0` and `npm dedupe` produced the following `package-lock.json`:
```json
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "@tootallnate/once": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/@tootallnate/once/-/once-1.0.0.tgz",
      "integrity": "sha512-KYyTT/T6ALPkIRd2Ge080X/BsXvy9O0hcWTtMWkPvwAwF99+vn6Dv4GzrFT/Nn1LePr+FFDbRXXlqmsy9lw2zA=="
    },
    "agent-base": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/agent-base/-/agent-base-6.0.0.tgz",
      "integrity": "sha512-j1Q7cSCqN+AwrmDd+pzgqc0/NpC655x2bUf5ZjRIO77DcNBFmh+OgRNzF6OKdCC9RSCb19fGd99+bhXFdkRNqw==",
      "requires": {
        "debug": "4"
      }
    },
    "console-menu": {
      "version": "0.1.0",
      "integrity": "sha1-Zbqm2/OuoMFdmd3zAuQLvD1d8z4=",
      "requires": {
        "keypress": "^0.2.1"
      }
    },
    "debug": {
      "version": "4.1.1",
      "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz",
      "integrity": "sha512-pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==",
      "requires": {
        "ms": "^2.1.1"
      }
    },
    "follow-redirects": {
      "version": "1.10.0",
      "resolved": "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.10.0.tgz",
      "integrity": "sha512-4eyLK6s6lH32nOvLLwlIOnr9zrL8Sm+OvW4pVTJNoXeGzYIkHVf+pADQi+OJ0E67hiuSLezPVPyBcIZO50TmmQ==",
      "requires": {
        "debug": "^3.0.0"
      },
      "dependencies": {
        "debug": {
          "version": "3.2.6",
          "resolved": "https://registry.npmjs.org/debug/-/debug-3.2.6.tgz",
          "integrity": "sha512-mel+jf7nrtEl5Pn1Qx46zARXKDpBbvzezse7p7LqINmdoIk8PYP5SySaxEmYv6TZ0JyEKA1hsCId6DIhgITtWQ==",
          "requires": {
            "ms": "^2.1.1"
          }
        }
      }
    },
    "http-proxy-agent": {
      "version": "4.0.1",
      "resolved": "https://registry.npmjs.org/http-proxy-agent/-/http-proxy-agent-4.0.1.tgz",
      "integrity": "sha512-k0zdNgqWTGA6aeIRVpvfVob4fL52dTfaehylg0Y4UvSySvOq/Y+BOyPrgpUrA7HylqvU8vIZGsRuXmspskV0Tg==",
      "requires": {
        "@tootallnate/once": "1",
        "agent-base": "6",
        "debug": "4"
      }
    },
    "https-proxy-agent": {
      "version": "5.0.0",
      "resolved": "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.0.tgz",
      "integrity": "sha512-EkYm5BcKUGiduxzSt3Eppko+PiNWNEpa4ySk9vTC6wDsQJW9rHSa+UhGNJoRYp7bz6Ht1eaRIa6QaJqO5rCFbA==",
      "requires": {
        "agent-base": "6",
        "debug": "4"
      }
    },
    "keypress": {
      "version": "0.2.1",
      "resolved": "https://registry.npmjs.org/keypress/-/keypress-0.2.1.tgz",
      "integrity": "sha1-HoBFQlABjbrUw/6USX1uZ7YmnHc="
    },
    "ms": {
      "version": "2.1.2",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz",
      "integrity": "sha512-sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w=="
    },
    "progress": {
      "version": "git://github.com/jasongin/node-progress.git#4a6c2fdc782cff6c9f8933339e7aae0b38d682d4",
      "from": "git://github.com/jasongin/node-progress.git"
    }
  }
}
```
Is it okay with you?

**Comment by jasongin** [comment]
That looks good. If you update the PR with those changes, I'll merge it.

**Comment by eternalphane** [comment]
Done.

**Comment by eternalphane** [comment]
Bump...

**Comment by rohantarai** [comment]
When it will be merged? After merging please release the windows msi installer also.

**Comment by JokerQyou** [comment]
Any chance this can be merged in the near future?

**Comment by rohantarai** [comment]
Thanks @jasongin for the merge. Can you please release the windows msi installer also.

**Comment by jasongin** [comment]
Yes. Planning to do that later today after I get through a few other updates.

**Comment by jasongin** [comment]
@rohantarai I published the v1.6.0 MSI: https://github.com/jasongin/nvs/releases/tag/v1.6.0

**Comment by rohantarai** [comment]
Thank you so much @jasongin

**Pull request merged**
