### PR TITLE
Add v8-canary version support

### PR DESCRIPTION
**Pull request by fengmk2**
https://nodejs.org/download/v8-canary/

### CODE REVIEW

**Comment by jasongin** [comment]
Hmm, the "zsh CLI" test failed in the Travis CI run. It doesn't appear related, but I'm investigating.

**Comment by ljharb** [comment]
I really strongly recommends not adding the support. The node team provided this canary with a lot of hesitation, because they did not want users to be broken by something this unstable.

**Comment by fengmk2** [comment]
@ljharb I only use the canary version on test env, try to test some new feature, not on the production env.

**Comment by jasongin** [comment]
Well, this change doesn't add anything that is actually specific to v8-canary builds. It just fixes a regex to allow additional hyphens in the semver (as in "v9.0.0-v8-canary20170609cd40078f1f"). Technically the regex was wrong before because additional hyphens should be allowed according to the semver spec.

**Comment by jasongin** [comment]
To get canary builds, you'd still have to add a remote. Something like this:
```
nvs remote v8-canary https://nodejs.org/download/v8-canary
nvs add v8-canary
```

I agree this remote URI should not be added to the defaults alongside regular node, nightly, and chakracore remote URIs. But if people really want to download canary builds, it doesn't make sense to block it because of the silly hyphen.

**Comment by ljharb** [comment]
@fengmk2 only v8 devs should be testing on the v8 canary, imo.

@jasongin lol fair point

**Comment by jasongin** [comment]
Merging, thanks!

I have a fix for the unrelated zsh issue that I'll merge separately.

**Pull request merged**
